import type { User } from '@supabase/supabase-js'
import type { GameProfile, Option, Player } from './models'

// Synthetic, local-only demo. Persona switching is not authentication; never use as a server authorization layer.
const KEY='mabar-finder.synthetic-demo.v3', SESSION='mabar-finder.synthetic-demo.persona.v1'
type Row=Record<string,any>
type Table='games'|'game_catalog_options'|'profiles'|'game_profiles'|'invites'|'conversations'|'messages'|'blocks'|'reports'|'user_roles'|'shares'
type State=Record<Table,Row[]>
const gameNames:[string,string][]=[['free-fire','Free Fire'],['mlbb','Mobile Legends: Bang Bang'],['pubg-mobile','PUBG Mobile'],['valorant','Valorant']]
const catalog:Record<string,Record<string,string[]>>={
 'mlbb':{rank:['warrior','elite','master','grandmaster','epic','legend','mythic','mythical-glory'],role:['tank','fighter','assassin','mage','marksman','support'],mode:['classic','ranked','brawl'],hero:['other']},
 'pubg-mobile':{rank:['bronze','silver','gold','platinum','diamond','crown','ace','conqueror'],role:['igl','rusher','support','sniper'],mode:['classic','arena'],perspective:['tpp','fpp'],team_size:['solo','duo','squad'],map:['erangel','miramar','sanhok','vikendi']},
 'free-fire':{rank:['bronze','silver','gold','platinum','diamond','heroic','grandmaster'],role:['rusher','support','sniper','igl'],mode:['battle-royale','clash-squad']},
 'valorant':{rank:['iron','bronze','silver','gold','platinum','diamond','ascendant','immortal','radiant'],role:['duelist','initiator','controller','sentinel'],mode:['competitive','unrated','swiftplay'],agent:['other']}
}
export const demoPersonas=[{id:'demo-player',name:'Naya (pemain)'},{id:'demo-rival',name:'Bima (pemain)'},{id:'demo-admin',name:'Rani (admin)'}] as const
const stamp=()=>new Date().toISOString(), uid=()=>`demo-${globalThis.crypto?.randomUUID?.()||Math.random().toString(36).slice(2)}`
const optionId=(slug:string,kind:string,code:string)=>`option-${slug}-${kind}-${code}`
function seed():State {
 const games=gameNames.map(([slug,name])=>({id:`game-${slug}`,slug,name,active:true}))
 const game_catalog_options:Option[]=games.flatMap(g=>Object.entries({...catalog[g.slug],region:['asia','sea','indonesia']}).flatMap(([kind,codes])=>codes.map((code,i)=>({id:optionId(g.slug,kind,code),game_id:g.id,kind,code,label:code.split('-').map(part=>part[0].toUpperCase()+part.slice(1)).join(' '),sort_order:i+1,rank_mode_option_id:kind==='rank'&&['free-fire','pubg-mobile'].includes(g.slug)?optionId(g.slug,'mode',g.slug==='free-fire'?'battle-royale':'classic'):null,active:true}))))
 for(const rank of catalog['free-fire'].rank){const original=game_catalog_options.find(o=>o.id===optionId('free-fire','rank',rank))!;game_catalog_options.push({...original,id:optionId('free-fire','rank',rank+'-cs'),code:rank+'-cs',rank_mode_option_id:optionId('free-fire','mode','clash-squad')})}
 const profiles=demoPersonas.map(({id,name})=>({user_id:id,display_name:name,bio:'Profil sintetis untuk mencoba Mabar Finder.',timezone:'Asia/Jakarta',languages:['id'],voice_preference:'flexible',play_style:'casual',availability_status:'ready',visibility:'public',account_status:'active',adult_declared_at:stamp()}))
 const game_profiles:GameProfile[]=games.flatMap((g,i)=>['demo-player','demo-rival','demo-admin'].map((user_id,j)=>({id:`profile-${i}-${j}`,user_id,game_id:g.id,ign:`${['Naya','Bima','Rani'][j]} Demo`,game_id_private:`DEMO-PRIVATE-${i}-${j}`,region_option_id:optionId(g.slug,'region','indonesia'),primary_rank_option_id:optionId(g.slug,'rank',g.slug==='free-fire'?'heroic':g.slug==='mlbb'?'epic':g.slug==='pubg-mobile'?'gold':'silver'),primary_rank_mode_option_id:g.slug==='free-fire'||g.slug==='pubg-mobile'?optionId(g.slug,'mode',g.slug==='free-fire'?'battle-royale':'classic'):null,primary_role_option_id:optionId(g.slug,'role',catalog[g.slug].role[j]),visibility:'public',status:'active',attributes:{},availability_status:'ready',created_at:stamp(),updated_at:stamp()})))
 return {games,game_catalog_options,profiles,game_profiles,invites:[{id:'invite-seeded',sender_id:'demo-rival',recipient_id:'demo-player',game_id:games[0].id,message:'Halo, ayo mabar! (data sintetis)',status:'pending',created_at:stamp(),expires_at:new Date(Date.now()+86400000).toISOString()}],conversations:[],messages:[],blocks:[],reports:[],user_roles:[{user_id:'demo-admin',role:'admin'}],shares:[]}
}
let memory:State|undefined, persona:string|null=null
function storage():Storage|undefined {try{return globalThis.localStorage}catch{return undefined}}
function state():State {if(!memory){try{memory=JSON.parse(storage()?.getItem(KEY)||'null') as State}catch{};if(!memory||!Array.isArray(memory.games))memory=seed()}return memory}
function save(){storage()?.setItem(KEY,JSON.stringify(state()))}
export function resetDemo(){memory=seed();storage()?.removeItem(KEY);storage()?.removeItem(SESSION);persona=null}
export function demoUserId(){const id=persona||(persona=storage()?.getItem(SESSION)||null);return demoPersonas.some(p=>p.id===id)?id:null}
export function demoUser():User|null {const id=demoUserId();if(!id)return null;const p=demoPersonas.find(x=>x.id===id)!;return {id,email:`${id}@example.invalid`,email_confirmed_at:stamp(),app_metadata:{provider:'demo'},user_metadata:{display_name:p.name},aud:'authenticated',created_at:stamp()} as User}
export function demoLogin(id:string){if(!demoPersonas.some(p=>p.id===id))throw new Error('Persona demo tidak tersedia');persona=id;storage()?.setItem(SESSION,id);return demoUser()!}
export function demoLogout(){persona=null;storage()?.removeItem(SESSION)}
function mustUser(){const id=demoUserId();if(!id)throw new Error('Masuk sebagai persona demo terlebih dahulu');return id}
function isActive(id:string){const p=state().profiles.find(p=>p.user_id===id);return p?.account_status==='active'&&!!p.adult_declared_at}
function ensureActive(){const id=mustUser();if(!isActive(id))throw new Error('Akun tidak aktif');return id}
function ensureAdmin(){const id=mustUser();if(!isActive(id)||!state().user_roles.some(r=>r.user_id===id&&r.role==='admin'))throw new Error('Akses admin ditolak')}
function blocked(a:string,b:string){return state().blocks.some(x=>(x.blocker_id===a&&x.blocked_id===b)||(x.blocker_id===b&&x.blocked_id===a))}
function conversation(id:string){const c=state().conversations.find(x=>x.id===id&&x.status==='active'&&state().invites.some(i=>i.id===x.invite_id&&i.status==='accepted')&&[x.participant_low,x.participant_high].includes(demoUserId())&&!blocked(x.participant_low,x.participant_high)&&isActive(x.participant_low)&&isActive(x.participant_high));return c||null}
function ensureConversation(id:string){const c=conversation(id);if(!c)throw new Error('Percakapan tidak tersedia');return c}
function publicPlayers(){const s=state();return s.game_profiles.filter(gp=>gp.visibility==='public'&&gp.status==='active'&&s.games.some(g=>g.id===gp.game_id&&g.active)&&s.profiles.some(p=>p.user_id===gp.user_id&&p.visibility==='public'&&isActive(p.user_id))&&!blocked(demoUserId()||'',gp.user_id))}
function player(gp:Row):Player {const s=state(),g=s.games.find(x=>x.id===gp.game_id),p=s.profiles.find(x=>x.user_id===gp.user_id),option=(id:string)=>s.game_catalog_options.find(x=>x.id===id)?.label||null;return {id:gp.id,user_id:gp.user_id,game_id:gp.game_id,game_name:g!.name,display_name:p!.display_name,avatar_url:null,ign:gp.ign,rank:option(gp.primary_rank_option_id),role:option(gp.primary_role_option_id),region:option(gp.region_option_id),ready:gp.availability_status==='ready'&&p!.availability_status==='ready',updated_at:gp.updated_at||stamp(),bio:p!.bio}}
function assertOption(id:any,game:string,kind:string){if(id!=null&&!state().game_catalog_options.some(o=>o.id===id&&o.game_id===game&&o.kind===kind))throw new Error('Opsi katalog tidak valid')}
function validateProfile(gp:Row,old?:Row){const s=state();if(old&&(gp.user_id!==old.user_id||gp.game_id!==old.game_id))throw new Error('Pemilik/game tidak dapat diganti');if(!s.games.some(g=>g.id===gp.game_id&&g.active))throw new Error('Game tidak aktif');if(!gp.ign?.trim()||gp.ign.length>64)throw new Error('IGN tidak valid');for(const [field,kind] of [['region_option_id','region'],['server_option_id','server'],['primary_rank_option_id','rank'],['primary_rank_mode_option_id','mode'],['primary_role_option_id','role']])assertOption(gp[field],gp.game_id,kind);if(gp.primary_rank_option_id&&s.game_catalog_options.find(o=>o.id===gp.primary_rank_option_id)?.rank_mode_option_id!==(gp.primary_rank_mode_option_id??null))throw new Error('Rank dan mode tidak cocok');if(gp.attributes&&(!Array.isArray(gp.attributes)&&typeof gp.attributes==='object'&&Object.keys(gp.attributes).every(k=>['stars','tier','perspective','team_size','play_goal'].includes(k))&&JSON.stringify(gp.attributes).length<=2048)===false)throw new Error('Atribut tidak diizinkan')}
function rpc(name:string,a:Row={}):any {
 const s=state();switch(name){
 case 'search_game_profiles':{if(!a.p_game_slug||a.p_limit!=null&&(a.p_limit<1||a.p_limit>50)||a.p_offset!=null&&(a.p_offset<0||a.p_offset>5000))throw new Error('Filter pencarian tidak valid');const game=s.games.find(g=>g.slug===a.p_game_slug&&g.active);let entries=publicPlayers().filter(g=>g.game_id===game?.id);const code=(id:string)=>s.game_catalog_options.find(o=>o.id===id)?.code;if(a.p_rank)entries=entries.filter(g=>{const r=code(g.primary_rank_option_id);return (!!a.p_mode||!['free-fire','pubg-mobile'].includes(a.p_game_slug))&&(r===a.p_rank||a.p_game_slug==='free-fire'&&a.p_mode==='clash-squad'&&r===a.p_rank+'-cs')&&(!a.p_mode||code(g.primary_rank_mode_option_id)===a.p_mode)});if(a.p_roles?.length)entries=entries.filter(g=>a.p_roles.includes(code(g.primary_role_option_id)));if(a.p_mode)entries=entries.filter(g=>code(g.primary_rank_mode_option_id)===a.p_mode);if(a.p_region)entries=entries.filter(g=>code(g.region_option_id)===a.p_region);if(a.p_ready!=null)entries=entries.filter(g=>(g.availability_status==='ready'&&s.profiles.find(p=>p.user_id===g.user_id)?.availability_status==='ready')===a.p_ready);return entries.slice(a.p_offset||0,(a.p_offset||0)+(a.p_limit||20)).map(player)}
 case 'public_profile_detail':{const gp=publicPlayers().find(g=>g.id===a.p_id);return gp?[player(gp)]:[]}
 case 'create_invite':{const sender=ensureActive();if(sender===a.p_recipient||!isActive(a.p_recipient)||blocked(sender,a.p_recipient)||!s.game_profiles.some(g=>g.user_id===sender&&g.game_id===a.p_game&&g.status==='active')||!publicPlayers().some(p=>p.user_id===a.p_recipient&&p.game_id===a.p_game)||String(a.p_message||'').length>500)throw new Error('Ajakan tidak diizinkan');if(s.invites.some(i=>i.status==='pending'&&i.game_id===a.p_game&&new Date(i.expires_at)>new Date()&&[i.sender_id,i.recipient_id].sort().join() === [sender,a.p_recipient].sort().join()))throw new Error('Ajakan masih menunggu');const row={id:uid(),sender_id:sender,recipient_id:a.p_recipient,game_id:a.p_game,message:a.p_message||null,status:'pending',created_at:stamp(),expires_at:new Date(Date.now()+7*86400000).toISOString()};s.invites.push(row);save();return {...row}}
 case 'respond_invite':case 'cancel_invite':{const id=name==='respond_invite'?ensureActive():mustUser(),invite=s.invites.find(i=>i.id===a.p_id&&i.status==='pending');if(!invite||(name==='cancel_invite'?invite.sender_id!==id:invite.recipient_id!==id))throw new Error('Ajakan tidak tersedia');if(name==='respond_invite'&&(blocked(invite.sender_id,invite.recipient_id)||!isActive(invite.sender_id)))throw new Error('Ajakan tidak diizinkan');invite.status=name==='cancel_invite'?'cancelled':new Date(invite.expires_at)<=new Date()?'expired':a.p_accept?'accepted':'rejected';if(invite.status==='accepted'){const participants=[invite.sender_id,invite.recipient_id].sort();s.conversations.push({id:uid(),invite_id:invite.id,participant_low:participants[0],participant_high:participants[1],status:'active',created_at:stamp()})}save();return {...invite}}
 case 'send_message':{const c=ensureConversation(a.p_conversation),body=String(a.p_body||'').trim();ensureActive();if(!body||body.length>2000)throw new Error('Pesan tidak diizinkan');const m={id:uid(),conversation_id:c.id,sender_id:mustUser(),body,created_at:stamp()};s.messages.push(m);save();return {...m}}
 case 'share_game_id':{const c=ensureConversation(a.p_conversation),gp=s.game_profiles.find(p=>p.id===a.p_game_profile&&p.user_id===ensureActive()&&p.status==='active'&&p.game_id===s.invites.find(i=>i.id===c.invite_id)?.game_id);if(!gp?.game_id_private)throw new Error('ID game tidak tersedia');s.shares=s.shares.filter(x=>!(x.conversation_id===c.id&&x.owner_id===mustUser()));const share={id:uid(),conversation_id:c.id,owner_id:mustUser(),game_profile_id:gp.id,revoked_at:null};s.shares.push(share);save();return share.id}
 case 'revoke_game_id_share':{const share=s.shares.find(x=>x.id===a.p_id&&x.owner_id===mustUser());if(!share)throw new Error('Bagian tidak tersedia');share.revoked_at=stamp();save();return null}
 case 'read_shared_game_id':{const c=conversation(a.p_conversation);if(!c||a.p_owner===demoUserId()||![c.participant_low,c.participant_high].includes(a.p_owner))return null;const share=s.shares.find(x=>x.conversation_id===c.id&&x.owner_id===a.p_owner&&!x.revoked_at),gp=s.game_profiles.find(g=>g.id===share?.game_profile_id&&g.user_id===a.p_owner&&g.status==='active'&&g.game_id===s.invites.find(i=>i.id===c.invite_id)?.game_id);return gp?.game_id_private||null}
 case 'create_report':{const user=ensureActive(),target=a.p_target_id,type=a.p_target_type;const valid=type==='profile'?s.game_profiles.some(p=>p.id===target&&p.user_id===a.p_reported):type==='invite'?s.invites.some(i=>i.id===target&&[i.sender_id,i.recipient_id].includes(user)&&[i.sender_id,i.recipient_id].includes(a.p_reported)):type==='message'?s.messages.some(m=>m.id===target&&m.sender_id===a.p_reported&&s.conversations.some(c=>c.id===m.conversation_id&&[c.participant_low,c.participant_high].includes(user))):false;const description=String(a.p_description||'').trim();if(user===a.p_reported||!['harassment','spam','fraud','impersonation','inappropriate'].includes(a.p_category)||description.length<10||description.length>2000||!valid||s.reports.some(r=>r.reporter_id===user&&r.target_type===type&&r.target_id===target&&Date.now()-Date.parse(r.created_at)<86400000))throw new Error('Laporan tidak valid');const row={id:uid(),reporter_id:user,reported_id:a.p_reported,category:a.p_category,description,target_type:type,target_id:target,status:'new',created_at:stamp()};s.reports.push(row);save();return row.id}
 case 'apply_moderation_action':{ensureAdmin();const subject=s.profiles.find(p=>p.user_id===a.p_subject),reason=String(a.p_reason||'').trim();if(!subject||a.p_subject===mustUser()||!['hide_profile','restrict_account','restore_profile','restore_account'].includes(a.p_action)||reason.length<10||reason.length>1000||a.p_report&&!s.reports.some(r=>r.id===a.p_report&&r.reported_id===a.p_subject))throw new Error('Tindakan tidak diizinkan');if(a.p_action==='restrict_account'||a.p_action==='restore_account')subject.account_status=a.p_action==='restrict_account'?'restricted':'active';else s.game_profiles.filter(p=>p.user_id===a.p_subject).forEach(p=>p.status=a.p_action==='hide_profile'?'hidden':'active');save();return uid()}
 case 'add_catalog_option':{ensureAdmin();const code=String(a.p_code||''),label=String(a.p_label||'').trim(),allowed=['rank','role','mode','region','server','map','hero','agent','perspective','team_size'];if(!s.games.some(g=>g.id===a.p_game)||!allowed.includes(a.p_kind)||!(/^[a-z0-9-]{2,50}$/.test(code))||label.length<2||label.length>80||s.game_catalog_options.some(o=>o.game_id===a.p_game&&o.kind===a.p_kind&&o.code===code))throw new Error('Opsi katalog tidak valid');if(a.p_rank_mode&&a.p_kind!=='rank')throw new Error('Mode hanya berlaku untuk rank');assertOption(a.p_rank_mode,a.p_game,'mode');const row={id:uid(),game_id:a.p_game,kind:a.p_kind,code,label,sort_order:0,rank_mode_option_id:a.p_rank_mode||null,active:true};s.game_catalog_options.push(row);save();return row.id}
 default:throw new Error(`RPC demo tidak didukung: ${name}`)
 }}
const profileFields=new Set(['display_name','avatar_url','bio','languages','timezone','voice_preference','play_style','availability_status','visibility'])
const gameProfileFields=new Set(['ign','game_id_private','region_option_id','server_option_id','primary_rank_option_id','primary_rank_mode_option_id','primary_role_option_id','play_goal','availability_status','visibility','attributes'])
class Query implements PromiseLike<{data:any;error:any}>{filters:((r:Row)=>boolean)[]=[];singleRow=false;maybe=false;limitCount=Infinity;descending=false;field='';selected=false;constructor(public table:Table,public action='select',public input:Row={}){}select(_columns='*'){this.selected=true;return this}eq(k:string,v:any){this.filters.push(r=>r[k]===v);return this}or(expr:string){const parts=expr.split(',').map(p=>p.split('.'));if(parts.some(p=>p.length!==3||p[1]!=='eq'||!['sender_id','recipient_id','participant_low','participant_high'].includes(p[0])))throw new Error('Filter demo tidak didukung');this.filters.push(r=>parts.some(([k,,v])=>String(r[k])===v));return this}order(k:string,{ascending=true}:any={}){this.field=k;this.descending=!ascending;return this}limit(n:number){this.limitCount=n;return this}single(){this.singleRow=true;return this}maybeSingle(){this.singleRow=true;this.maybe=true;return this}
 then<TResult1={data:any;error:any},TResult2=never>(resolve?:((value:{data:any;error:any})=>TResult1|PromiseLike<TResult1>)|null,reject?:((reason:any)=>TResult2|PromiseLike<TResult2>)|null):Promise<TResult1|TResult2>{return Promise.resolve().then(()=>{try{const s=state(),rows=s[this.table];if(!rows)throw new Error('Tabel demo tidak tersedia');const me=demoUserId(),admin=me&&s.user_roles.some(r=>r.user_id===me&&r.role==='admin')&&isActive(me);let matched=rows.filter(r=>this.filters.every(f=>f(r)));if(this.action==='select'){switch(this.table){case 'profiles':case 'game_profiles':case 'user_roles':matched=matched.filter(r=>!!me&&r.user_id===me);break;case 'invites':matched=matched.filter(r=>!!me&&[r.sender_id,r.recipient_id].includes(me));break;case 'conversations':matched=matched.filter(r=>!!conversation(r.id));break;case 'messages':matched=matched.filter(r=>!!conversation(r.conversation_id)&&!r.deleted_at);break;case 'blocks':matched=matched.filter(r=>r.blocker_id===me);break;case 'reports':matched=matched.filter(r=>r.reporter_id===me||admin);break;case 'shares':matched=matched.filter(r=>r.owner_id===me&&!!conversation(r.conversation_id));break;case 'games':case 'game_catalog_options':matched=matched.filter(r=>r.active||admin);break}}else{const user=ensureActive();if(this.table==='blocks'){if(this.action!=='insert'||this.input.blocker_id!==user||this.input.blocked_id===user||!s.profiles.some(p=>p.user_id===this.input.blocked_id)||s.blocks.some(b=>b.blocker_id===user&&b.blocked_id===this.input.blocked_id))throw new Error('Blokir ditolak');const row={blocker_id:user,blocked_id:this.input.blocked_id,created_at:stamp()};rows.push(row);matched=[row]}else if(this.table==='profiles'||this.table==='game_profiles'){if(this.action==='update'){matched=matched.filter(r=>r.user_id===user);if(!matched.length||Object.keys(this.input).some(k=>!(this.table==='profiles'?profileFields:gameProfileFields).has(k)))throw new Error('Profil tidak tersedia');const pending=matched.map(r=>({...r,...this.input}));if(this.table==='game_profiles')pending.forEach((r,i)=>validateProfile(r,matched[i]));matched.forEach((r,i)=>Object.assign(r,pending[i],{updated_at:stamp()}))}else if(this.action==='insert'&&this.table==='game_profiles'&&this.input.user_id===user&&!s.game_profiles.some(g=>g.user_id===user&&g.game_id===this.input.game_id)){const row={...this.input,id:uid(),status:'active',availability_status:this.input.availability_status||'ready',visibility:this.input.visibility||'public',attributes:this.input.attributes||{},created_at:stamp(),updated_at:stamp()};validateProfile(row);rows.push(row);matched=[row]}else throw new Error('Mutasi profil ditolak')}else throw new Error('Mutasi tabel tidak tersedia');save()}
 if(this.field)matched.sort((a,b)=>String(a[this.field]||'').localeCompare(String(b[this.field]||''))*(this.descending?-1:1));const data=this.action!=='select'&&!this.selected?null:this.singleRow?matched[0]?structuredClone(matched[0]):null:structuredClone(matched.slice(0,this.limitCount));return {data,error:!data&&this.singleRow&&!this.maybe?{message:'Data tidak tersedia'}:null}}catch(e){return {data:null,error:{message:(e as Error).message}}}}).then(resolve,reject)}}
export const demoBackend={from(table:Table){return {select(columns='*'){return new Query(table).select(columns)},update(input:Row){return new Query(table,'update',input)},insert(input:Row){return new Query(table,'insert',input)}}},async rpc(name:string,args:Row={}){try{return {data:rpc(name,args),error:null}}catch(e){return {data:null,error:{message:(e as Error).message}}}},auth:{async getUser(){return {data:{user:demoUser()},error:null}},async signOut(){demoLogout();return {error:null}}}}
