<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import AdminShell from '../components/AdminShell.vue'
import { useSessionStore } from '../stores/session'
import { requireBackend, supabase } from '../lib/supabase'
type Report={id:string;reporter_id:string;reported_id:string;category:string;description:string;status:string;created_at:string;target_type?:string;target_id?:string}
const session=useSessionStore(), reports=ref<Report[]>([]), selectedId=ref(''),filter=ref('all'),reason=ref(''),action=ref('hide_profile'),loading=ref(false),busy=ref(false),error=ref(''),notice=ref('')
const selected=computed(()=>reports.value.find(r=>r.id===selectedId.value))
const visible=computed(()=>reports.value.filter(r=>filter.value==='all'||r.status===filter.value))
function selectFilter(value:string){filter.value=value;selectedId.value=visible.value[0]?.id||''}
const active=computed(()=>Boolean(selected.value))
function date(value:string){return new Date(value).toLocaleString('id-ID',{dateStyle:'medium',timeStyle:'short'})}
async function load(){if(!supabase||!session.user||!session.admin)return;loading.value=true;error.value='';try{const {data,error:failure}=await requireBackend().from('reports').select('id,reporter_id,reported_id,category,description,status,created_at,target_type,target_id').order('created_at',{ascending:false}).limit(100);if(failure)throw failure;reports.value=(data||[]) as Report[];if(!reports.value.some(r=>r.id===selectedId.value)||!visible.value.some(r=>r.id===selectedId.value))selectedId.value=visible.value[0]?.id||''}catch{error.value='Laporan tidak dapat dimuat. Periksa izin admin dan koneksi.'}finally{loading.value=false}}
async function moderate(){const r=selected.value;if(!supabase||!session.user||!session.admin||!r||busy.value||!active.value||r.reported_id===session.user.id)return;if(reason.value.trim().length<10){error.value='Alasan tindakan minimal 10 karakter.';return}if(!confirm(`Terapkan ${action.value} untuk laporan ini? Tindakan dicatat pada audit.`))return;busy.value=true;error.value='';notice.value='';try{const {error:failure}=await requireBackend().rpc('apply_moderation_action',{p_subject:r.reported_id,p_report:r.id,p_action:action.value,p_reason:reason.value.trim()});if(failure)throw failure;notice.value='Tindakan moderasi tercatat. Status laporan hanya berubah jika backend memperbaruinya.';reason.value='';await load()}catch{error.value='Tindakan ditolak. Periksa izin dan target laporan.'}finally{busy.value=false}}
onMounted(load)
</script>
<template>
  <AdminShell title="Pusat Laporan & Moderasi" subtitle="Tinjau aduan komunitas, baca kronologi, lalu ambil tindakan yang dicatat backend.">
    <template #actions><button class="secondary" :disabled="loading" @click="load">Muat ulang</button></template>
    <p v-if="error" role="alert" class="error">{{ error }}</p><p v-if="notice" role="status" class="notice">{{ notice }}</p><p v-if="loading" role="status">Memuat laporan…</p>
    <template v-if="!loading"><div class="summary"><span>Total terlihat: <strong>{{ reports.length }}{{ reports.length===100?'+':'' }}</strong></span><span>Baru: <strong>{{ reports.filter(r=>r.status==='new'||r.status==='open').length }}</strong></span><span>Ditinjau: <strong>{{ reports.filter(r=>r.status==='reviewing').length }}</strong></span><span>Selesai: <strong>{{ reports.filter(r=>r.status==='resolved'||r.status==='dismissed').length }}</strong></span></div>
    <nav class="filters" aria-label="Filter laporan"><button v-for="option in [{value:'all',text:'Semua'},{value:'new',text:'Baru'},{value:'reviewing',text:'Ditinjau'},{value:'resolved',text:'Selesai'},{value:'dismissed',text:'Ditutup'}]" :key="option.value" :class="{current:filter===option.value}" :aria-pressed="filter===option.value" @click="selectFilter(option.value)">{{ option.text }}</button></nav>
    <div class="split"><section class="panel"><h2>Daftar tiket antrean</h2><p v-if="!visible.length">Tidak ada laporan sesuai filter.</p><div class="tickets"><button v-for="r in visible" :key="r.id" class="ticket" :class="{selected:selectedId===r.id}" @click="selectedId=r.id"><span class="ticket-top"><strong>{{ r.category }}</strong><span>{{ r.status }}</span></span><small>{{ date(r.created_at) }}</small><span class="parties">Pelapor: {{ r.reporter_id }}<br>Terlapor: {{ r.reported_id }}</span><span class="excerpt">{{ r.description }}</span><span class="more">Lihat detail laporan</span></button></div></section>
    <aside v-if="selected" class="panel details"><div class="detail-head"><h2>Detail laporan</h2><span>{{ selected.status }}</span></div><p>{{ date(selected.created_at) }}</p><dl><dt>Kategori</dt><dd>{{ selected.category }}</dd><dt>Pelapor</dt><dd>{{ selected.reporter_id }}</dd><dt>Terlapor</dt><dd>{{ selected.reported_id }}</dd><dt>Target</dt><dd>{{ selected.target_type||'Tidak tersedia' }} | {{ selected.target_id||'Tidak tersedia' }}</dd></dl>
      <p v-if="selected.target_type==='profile'&&selected.target_id"><RouterLink :to="`/profil/${selected.target_id}`">Buka profil yang dilaporkan</RouterLink> (mungkin tidak terlihat bila disembunyikan).</p><p v-else>Link ke target ini belum tersedia dari halaman profil publik.</p>
      <h3>Kronologi aduan</h3><blockquote>{{ selected.description }}</blockquote><p>Lampiran bukti, skor reputasi, dan deteksi otomatis: <strong>Tidak tersedia</strong>.</p>
      <div class="unsupported"><button disabled title="Backend belum memiliki operasi mengubah status laporan">Tandai ditinjau</button><button disabled title="Backend belum memiliki operasi menutup laporan tanpa tindakan moderasi">Tutup laporan</button></div><p>Status laporan tidak dapat diubah sendiri. RPC mencatat tindakan moderasi tanpa mengubah status laporan.</p>
      <form @submit.prevent="moderate"><h3>Tindakan moderasi</h3><label>Pilih tindakan<select v-model="action"><option value="hide_profile">Sembunyikan profil game</option><option value="restrict_account">Batasi akun</option><option value="restore_profile">Pulihkan profil game</option><option value="restore_account">Pulihkan akun</option></select></label><label>Alasan audit<textarea v-model="reason" required minlength="10" maxlength="1000" rows="4" placeholder="Jelaskan alasan tindakan (minimal 10 karakter)"></textarea></label><button type="submit" :disabled="busy||!active||selected.reported_id===session.user?.id">{{ busy?'Mencatat tindakan…':'Terapkan tindakan' }}</button><p v-if="selected.reported_id===session.user?.id">Admin tidak dapat memoderasi diri sendiri.</p></form></aside></div></template>
  </AdminShell>
</template>
<style scoped>
.summary,.panel{background:#1e1e29;border:1px solid #41414f;border-radius:20px;padding:22px}.summary{display:flex;flex-wrap:wrap;gap:12px 25px}.summary span{color:#b9b9c7;font-size:14px}.summary strong{color:#c8ff4d}.filters{display:flex;gap:8px;margin:18px 0;overflow-x:auto;padding-bottom:4px}.filters button{white-space:nowrap}.filters button.current{background:#c8ff4d;color:#14141c}.split{display:grid;grid-template-columns:minmax(0,5fr) minmax(310px,4fr);align-items:start;gap:16px}.panel h2{font:750 20px 'Plus Jakarta Sans',sans-serif;margin:0 0 18px}.panel p{color:#b9b9c7;line-height:1.6;font-size:13px}.tickets{display:grid;gap:10px}.ticket{display:grid;text-align:left;gap:9px;background:#292936;color:#f5f3ee;border:1px solid #444451;border-radius:15px;padding:15px;white-space:normal}.ticket.selected{border-color:#c8ff4d}.ticket-top,.detail-head{display:flex;justify-content:space-between;align-items:center;gap:12px}.ticket-top>span,.detail-head>span{border:1px solid #676776;border-radius:100px;padding:4px 10px;font-size:12px}.ticket small,.parties{color:#b9b9c7;overflow-wrap:anywhere;font-size:12px}.excerpt{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:13px}.more,.details a{color:#c8ff4d;font-size:13px}.details dl{display:grid;grid-template-columns:100px minmax(0,1fr);gap:10px;font-size:13px}.details dt{color:#aeadba}.details dd{margin:0;overflow-wrap:anywhere}.details h3{font-size:16px;margin:24px 0 10px}.details blockquote{white-space:pre-wrap;overflow-wrap:anywhere;background:#292936;border-left:3px solid #8b7cff;padding:15px;margin:0;line-height:1.6}.unsupported{display:flex;flex-wrap:wrap;gap:8px;margin-top:20px}form{border-top:1px solid #484854;padding-top:5px;display:grid;gap:14px}label{display:grid;gap:8px;font-size:13px}textarea,select{background:#292936;color:#f5f3ee;border:1px solid #5a5a68;border-radius:11px;padding:11px;font:inherit;max-width:100%}button{border:0;border-radius:100px;background:#333340;color:#f5f3ee;padding:10px 14px;font-weight:700;cursor:pointer}button.secondary{background:#c8ff4d;color:#14141c}form button{background:#c8ff4d;color:#14141c}button:disabled{opacity:.5;cursor:not-allowed}.error{color:#ffb4ab}.notice{color:#c8ff4d}:focus-visible{outline:3px solid #8b7cff;outline-offset:2px}@media(max-width:900px){.split{grid-template-columns:1fr}}
</style>
