<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import AdminShell from '../components/AdminShell.vue'
import { useSessionStore } from '../stores/session'
import { requireBackend } from '../lib/supabase'
import type { Option } from '../lib/models'
type Game = {id:string;name:string;slug:string}
const session=useSessionStore(), games=ref<Game[]>([]), options=ref<Option[]>([]),gameId=ref(''),loading=ref(false),busy=ref(false),error=ref(''),notice=ref('')
const kinds=['rank','role','mode','region','server','map','hero','agent','perspective','team_size'] as const
const kind=ref<(typeof kinds)[number]>('role'),code=ref(''),label=ref(''),rankMode=ref('')
const grouped=computed(()=>kinds.map(type=>({kind:type,options:options.value.filter(o=>o.kind===type)})).filter(group=>group.options.length))
const modeOptions=computed(()=>options.value.filter(o=>o.kind==='mode'))
async function loadGames(){if(!session.user||!session.admin)return;loading.value=true;error.value='';try{const {data,error:failure}=await requireBackend().from('games').select('id,name,slug,active').order('name');if(failure)throw failure;games.value=(data||[]) as Game[];if(!games.value.some(g=>g.id===gameId.value))gameId.value=games.value[0]?.id||'';await loadOptions()}catch{error.value='Daftar game tidak dapat dimuat.'}finally{loading.value=false}}
async function loadOptions(){options.value=[];if(!session.user||!session.admin||!gameId.value)return;loading.value=true;error.value='';try{const {data,error:failure}=await requireBackend().from('game_catalog_options').select('id,game_id,kind,code,label,sort_order,rank_mode_option_id,active').eq('game_id',gameId.value).order('sort_order');if(failure)throw failure;options.value=(data||[]) as Option[]}catch{error.value='Atribut game tidak dapat dimuat.'}finally{loading.value=false}}
async function addOption(){if(!session.user||!session.admin||busy.value)return;error.value='';notice.value='';const normalized=code.value.trim();const title=label.value.trim();if(!/^[a-z0-9-]{2,50}$/.test(normalized)||title.length<2||title.length>80){error.value='Kode harus 2–50 karakter kecil, angka atau tanda hubung; label 2–80 karakter.';return}
  busy.value=true;try{const {error:failure}=await requireBackend().rpc('add_catalog_option',{p_game:gameId.value,p_kind:kind.value,p_code:normalized,p_label:title,p_rank_mode:kind.value==='rank'&&rankMode.value?rankMode.value:null});if(failure)throw failure;code.value='';label.value='';rankMode.value='';notice.value='Opsi katalog ditambahkan.';await loadOptions()}catch(e){error.value=e instanceof Error?e.message:'Opsi gagal disimpan. Periksa izin dan kode yang unik.'}finally{busy.value=false}}
onMounted(loadGames)
</script>
<template>
  <AdminShell title="Kelola Skema Atribut Game" subtitle="Atur pilihan rank, role, mode, dan wilayah yang tersedia untuk profil game dan filter pencarian.">
    <section class="panel intro"><label for="attribute-game">Pilih game yang dikonfigurasi</label><select id="attribute-game" v-model="gameId" :disabled="busy||loading" @change="loadOptions"><option v-for="game in games" :key="game.id" :value="game.id">{{ game.name }}</option></select><button type="button" class="secondary" :disabled="loading" @click="loadGames">Muat ulang</button></section>
    <p v-if="error" class="error" role="alert">{{ error }}</p><p v-if="notice" class="notice" role="status">{{ notice }}</p><p v-if="loading" role="status">Memuat atribut…</p>
    <div v-if="!loading&&gameId" class="layout"><div>
      <section class="panel"><h2>Daftar variabel & pilihan</h2><p>Penambahan opsi muncul di daftar katalog. Pengubahan dan penghapusan atribut/opsi, urutan, dan aturan wajib isi belum didukung.</p><p v-if="!grouped.length">Belum ada opsi untuk game ini.</p><div v-for="group in grouped" :key="group.kind" class="group"><div class="group-title"><h3>{{ group.kind }}</h3><span>{{ group.options.length }} pilihan</span></div><ul><li v-for="option in group.options" :key="option.id"><span><strong>{{ option.label }}</strong> <small>{{ option.code }}</small><small v-if="option.rank_mode_option_id">Mode rank: {{ modeOptions.find(o=>o.id===option.rank_mode_option_id)?.label||'Tidak tersedia' }}</small></span><span class="row-actions"><span v-if="(option as Option & {active?:boolean}).active===false">Nonaktif</span><button type="button" disabled title="Pengubahan opsi belum didukung">Edit</button><button type="button" disabled title="Penghapusan opsi belum didukung">Hapus</button></span></li></ul></div></section>
    </div><aside class="panel"><h2>Tambah opsi katalog</h2><p>Jenis atribut berasal dari skema backend. Atribut angka/teks dan perubahan aturan form belum dapat dibuat dari panel ini.</p><form @submit.prevent="addOption"><label>Jenis atribut<select v-model="kind"><option v-for="type in kinds" :key="type" :value="type">{{ type }}</option></select></label><label>Kode unik<input v-model="code" required pattern="[a-z0-9-]{2,50}" maxlength="50" placeholder="contoh: duelist"></label><label>Label pemain<input v-model="label" required minlength="2" maxlength="80" placeholder="Contoh: Duelist"></label><label v-if="kind==='rank'">Mode rank (jika diperlukan)<select v-model="rankMode"><option value="">Tanpa mode</option><option v-for="mode in modeOptions" :key="mode.id" :value="mode.id">{{ mode.label }}</option></select></label><button type="submit" :disabled="busy||!gameId">{{ busy?'Menyimpan…':'Tambah opsi' }}</button></form><p class="muted">Hapus atribut, impor template, dan simpan keseluruhan skema belum didukung backend.</p></aside></div>
  </AdminShell>
</template>
<style scoped>
.panel{background:#1e1e29;border:1px solid #414150;border-radius:20px;padding:24px}.intro{display:flex;align-items:center;gap:12px;flex-wrap:wrap;margin-bottom:20px}.intro label{font-weight:700}.layout{display:grid;grid-template-columns:minmax(0,1fr) minmax(270px,350px);align-items:start;gap:18px}.panel h2{font:750 20px 'Plus Jakarta Sans',sans-serif;margin:0 0 12px}.panel p{color:#b9b9c7;line-height:1.6;font-size:13px}.group{background:#272733;border:1px solid #454554;border-radius:16px;padding:16px;margin-top:14px}.group-title{display:flex;align-items:center;justify-content:space-between;text-transform:capitalize}.group h3{margin:0 0 12px;font-size:18px}.group-title span{font-size:12px;color:#b9b9c7}ul{list-style:none;margin:0;padding:0}li{display:flex;justify-content:space-between;align-items:center;gap:8px;padding:10px 0;border-top:1px solid #484855;overflow-wrap:anywhere}li>span:first-child{min-width:0;display:grid;gap:2px}small{font-size:11px;color:#b8b8c8}.row-actions{white-space:nowrap}form,label:not(.intro label){display:grid;gap:8px}form{margin-top:20px;gap:18px}label{font-size:13px;font-weight:650}input,select{background:#2a2a37;color:#f5f3ee;border:1px solid #5a5a68;border-radius:11px;padding:10px 12px;font:inherit;max-width:100%}button{background:#c8ff4d;color:#14141c;border:0;border-radius:100px;padding:11px 16px;font-weight:750;cursor:pointer}.secondary{background:#333341;color:#f5f3ee}button:disabled{opacity:.5;cursor:not-allowed}.row-actions button{background:none;color:#b9b9c7;padding:5px}.error{color:#ffb4ab}.notice{color:#c8ff4d}:focus-visible{outline:3px solid #8b7cff;outline-offset:2px}@media(max-width:900px){.layout{grid-template-columns:1fr}}@media(max-width:540px){.panel{padding:16px}li{align-items:start;flex-direction:column}}
</style>
