<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import AdminShell from '../components/AdminShell.vue'
import { useSessionStore } from '../stores/session'
import { demoMode, requireBackend } from '../lib/supabase'
type Report={id:string;reported_id:string;category:string;description:string;status:string;created_at:string;target_type?:string;target_id?:string}
type Action={subject_user_id:string;action:string;created_at:string}
const session=useSessionStore(),reports=ref<Report[]>([]),actions=ref<Action[]>([]),selected=ref(''),search=ref(''),status=ref('all'),reason=ref(''),loading=ref(false),busy=ref(false),error=ref(''),notice=ref('')
const subjects=computed(()=>[...new Set(reports.value.map(r=>r.reported_id))].map(id=>({id,reports:reports.value.filter(r=>r.reported_id===id),latest:actions.value.find(a=>a.subject_user_id===id)})))
const visible=computed(()=>subjects.value.filter(s=>(status.value==='all'||(status.value==='reported'?s.reports.some(r=>r.status==='new'||r.status==='open'||r.status==='reviewing'):s.latest?.action===status.value))&&s.id.toLowerCase().includes(search.value.trim().toLowerCase())))
const detail=computed(()=>subjects.value.find(s=>s.id===selected.value))
async function load(){if(!session.user||!session.admin)return;loading.value=true;error.value='';try{const r=await requireBackend().from('reports').select('id,reported_id,category,description,status,created_at,target_type,target_id').order('created_at',{ascending:false}).limit(100);if(r.error)throw r.error;reports.value=(r.data||[]) as Report[];if(!demoMode){const a=await requireBackend().from('moderation_actions').select('subject_user_id,action,created_at').order('created_at',{ascending:false}).limit(100);if(a.error)throw a.error;actions.value=(a.data||[]) as Action[]}else actions.value=[];if(!subjects.value.some(s=>s.id===selected.value))selected.value=''}catch{error.value='Daftar akun terlapor tidak dapat dimuat. Periksa izin admin dan koneksi.'}finally{loading.value=false}}
async function moderate(action:'restrict_account'|'restore_account'){if(!session.user||!session.admin||busy.value||!detail.value||detail.value.id===session.user.id)return;if(reason.value.trim().length<10){error.value='Alasan minimal 10 karakter.';return}if(!confirm(`Terapkan tindakan ${action} pada akun ini? Tindakan akan dicatat.`))return;busy.value=true;error.value='';notice.value='';try{const result=await requireBackend().rpc('apply_moderation_action',{p_subject:detail.value.id,p_action:action,p_reason:reason.value.trim(),p_report:null});if(result.error)throw result.error;notice.value=demoMode?'Tindakan demo diterapkan pada data sintetis.':'Tindakan tercatat dalam audit moderasi.';reason.value='';await load()}catch{error.value='Tindakan ditolak. Periksa izin dan status akun.'}finally{busy.value=false}}
onMounted(load)
</script>
<template>
  <AdminShell title="Kelola Pengguna" subtitle="Tinjau akun terlapor dan tindakan moderasi. Direktori semua pengguna, email, reputasi, serta verifikasi tidak tersedia dari backend.">
    <template #actions><button class="primary" :disabled="loading" @click="load">Muat ulang</button></template>
    <section class="stats"><div><strong>{{ subjects.length }}</strong><span>Akun terlapor dalam 100 laporan terbaru</span></div><div><strong>{{ reports.filter(r=>['new','open','reviewing'].includes(r.status)).length }}</strong><span>Laporan perlu ditinjau</span></div><div><strong>Tidak tersedia</strong><span>Total pengguna terdaftar</span></div></section>
    <p v-if="error" role="alert" class="error">{{ error }}</p><p v-if="notice" role="status" class="notice">{{ notice }}</p><p v-if="loading" role="status">Memuat akun terlapor…</p>
    <section class="panel" v-if="!loading"><h2>Daftar akun terlapor</h2><p>Hanya akun yang muncul dalam 100 laporan terbaru. Status akun langsung tidak dapat dibaca; tindakan terakhir bukan status akun saat ini.</p><div class="filters"><label>Cari ID akun <input type="search" v-model="search" placeholder="Cari ID terlapor"></label><label>Filter <select v-model="status"><option value="all">Semua</option><option value="reported">Laporan terbuka</option><option v-if="!demoMode" value="restrict_account">Tindakan terakhir: dibatasi</option><option v-if="!demoMode" value="restore_account">Tindakan terakhir: dipulihkan</option></select></label></div>
    <div v-if="visible.length" class="table-wrap"><table><thead><tr><th>Akun</th><th>Email</th><th>Profil game</th><th>Laporan terlihat</th><th>Tindakan terakhir</th><th>Aksi</th></tr></thead><tbody><tr v-for="subject in visible" :key="subject.id"><td><span class="avatar" aria-hidden="true">ID</span><code>{{ subject.id }}</code></td><td>Tidak tersedia</td><td>Tidak tersedia</td><td>{{ subject.reports.length }}</td><td>{{ subject.latest?.action||'Tidak tersedia' }}</td><td><button class="secondary" @click="selected=subject.id">Detail</button></td></tr></tbody></table></div><p v-else>Tidak ada akun terlapor sesuai filter.</p></section>
    <div v-if="detail" class="backdrop" @click.self="selected=''" @keydown.esc="selected=''" role="presentation"><aside class="drawer" role="dialog" aria-modal="true" aria-label="Detail akun terlapor"><div class="drawer-head"><h2>Detail pengguna</h2><button class="secondary" aria-label="Tutup detail" @click="selected=''">Tutup</button></div><p class="identifier">{{ detail.id }}</p><p>Nama, email, tanggal bergabung, status terkini, dan riwayat aktivitas lengkap: <strong>Tidak tersedia</strong>.</p><p>{{ detail.reports.length }} laporan terlihat. Tindakan moderasi terakhir: {{ detail.latest?.action||'Tidak tersedia' }}.</p><h3>Riwayat laporan terbaru</h3><ul><li v-for="report in detail.reports" :key="report.id"><strong>{{ report.category }}</strong> ({{ report.status }})<p>{{ report.description }}</p></li></ul><form @submit.prevent><label>Alasan tindakan (min. 10 karakter)<textarea v-model="reason" required minlength="10" maxlength="1000" rows="3" placeholder="Jelaskan alasan yang dapat diaudit"></textarea></label><div class="actions"><button type="button" :disabled="busy||detail.id===session.user?.id" @click="moderate('restrict_account')">Batasi akun</button><button type="button" class="secondary" :disabled="busy||detail.id===session.user?.id" @click="moderate('restore_account')">Pulihkan akun</button></div><p v-if="detail.id===session.user?.id">Tindakan pada akun admin sendiri tidak diizinkan.</p><p>Hapus akun, ubah profil dan reset kata sandi belum didukung backend.</p></form></aside></div>
  </AdminShell>
</template>
<style scoped>
.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.stats>div,.panel{background:#1e1e29;border:1px solid #434350;border-radius:20px;padding:22px}.stats>div{display:flex;flex-direction:column;gap:9px}.stats strong{font:800 clamp(18px,3vw,30px) 'Plus Jakarta Sans',sans-serif;color:#c8ff4d}.stats span,.panel p,.drawer p{color:#b9b9c7;font-size:13px;line-height:1.6}.panel{margin-top:20px}.panel h2,.drawer h2{font:750 20px 'Plus Jakarta Sans',sans-serif;margin:0}.filters,.actions,.drawer-head{display:flex;gap:12px;align-items:center;flex-wrap:wrap}.filters{margin:18px 0}.filters label,form label{display:grid;gap:8px;font-size:13px}.filters input,.filters select,textarea{background:#2d2d39;border:1px solid #585865;color:#f5f3ee;border-radius:10px;padding:11px;font:inherit;max-width:100%}.table-wrap{overflow-x:auto}table{min-width:690px;width:100%;border-collapse:collapse;text-align:left}td,th{border-bottom:1px solid #3e3e4c;padding:12px 8px;font-size:13px}th{color:#b9b9c7}.avatar{display:inline-grid;place-items:center;border-radius:50%;width:32px;height:32px;margin-right:8px;background:#39334d;color:#d2caff;font-size:11px;font-weight:800}code,.identifier{overflow-wrap:anywhere}button{border:0;border-radius:100px;padding:10px 16px;font:700 13px inherit;background:#c8ff4d;color:#14141c;cursor:pointer}.secondary{background:#363642;color:#f5f3ee}button:disabled{opacity:.5;cursor:not-allowed}.backdrop{position:fixed;inset:0;background:#14141ccd;z-index:55;display:flex;justify-content:flex-end}.drawer{height:100%;width:min(450px,100%);overflow-y:auto;padding:26px;box-sizing:border-box;background:#1e1e29;border-left:1px solid #555561;border-radius:22px 0 0 22px}.drawer-head{justify-content:space-between}.drawer ul{padding-left:20px}.drawer li{margin:18px 0}.drawer form{display:grid;gap:16px}.error{color:#ffb4ab}.notice{color:#c8ff4d}:focus-visible{outline:3px solid #8b7cff;outline-offset:2px}@media(max-width:740px){.stats{grid-template-columns:1fr}}
</style>
